baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "The Woman's Journal Digital Archive"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Issues"
    url = "/issues/"
    weight = 3
  [[menu.main]]
    name = "Analysis"
    url = "/analysis/"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "People"
    url = "/people/"
    weight = 2
